"""add big integer

Revision ID: 1612e4b7a8fb
Revises: effcece59dd5
Create Date: 2023-08-09 17:24:50.008347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1612e4b7a8fb'
down_revision = 'effcece59dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_id')
    op.drop_column('transaction', 'transactison_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transactison_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
