"""add shange update badge

Revision ID: 6b00929902e8
Revises: cc890dca01ef
Create Date: 2023-08-18 17:55:04.302744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b00929902e8'
down_revision = 'cc890dca01ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
