"""add big integer

Revision ID: 6d82517e19eb
Revises: 5c627d53450a
Create Date: 2023-08-09 17:19:56.996377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d82517e19eb'
down_revision = '5c627d53450a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
