"""Initial migration

Revision ID: 716bd48ce72d
Revises: 
Create Date: 2023-08-06 23:10:06.623077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716bd48ce72d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
