"""add shange update badge

Revision ID: c008240a43a0
Revises: 2d257c9f9d34
Create Date: 2023-08-18 17:57:11.913571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c008240a43a0'
down_revision = '2d257c9f9d34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_badge', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_badge')
    # ### end Alembic commands ###
