"""add big integer

Revision ID: c8e3326a86b1
Revises: 1612e4b7a8fb
Create Date: 2023-08-09 17:24:57.561241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e3326a86b1'
down_revision = '1612e4b7a8fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_id')
    # ### end Alembic commands ###
