"""add update_badge

Revision ID: cc890dca01ef
Revises: 89ca25037895
Create Date: 2023-08-11 02:59:15.792289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc890dca01ef'
down_revision = '89ca25037895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_badge', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_badge')
    # ### end Alembic commands ###
