"""add big integer

Revision ID: e208f4397a40
Revises: 6d82517e19eb
Create Date: 2023-08-09 17:22:27.856745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e208f4397a40'
down_revision = '6d82517e19eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
