"""add big integer

Revision ID: effcece59dd5
Revises: e208f4397a40
Create Date: 2023-08-09 17:24:23.694459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effcece59dd5'
down_revision = 'e208f4397a40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transactison_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transactison_id')
    # ### end Alembic commands ###
