"""add payment

Revision ID: fdabd07c1764
Revises: 716bd48ce72d
Create Date: 2023-08-06 23:36:11.684927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdabd07c1764'
down_revision = '716bd48ce72d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pay_in_mouth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pay_in_mouth')
    # ### end Alembic commands ###
